apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app-v100
  template:
    metadata:
      labels:
        app: spring-boot-app-v100
    spec:
      containers:
        - name: spring-boot-app-v100
          image: thomasdachpc/cicdpipelineproject:v1.0.0
          ports:
            - containerPort: 8080
