apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-app-v100
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080